config:
  target: "http://localhost:3000"
  phases:
    - duration: 60
      arrivalRate: 10
      name: Warm up
    - duration: 60
      arrivalRate: 10
      rampTo: 250
      name: Ramp up
    - duration: 120
      arrivalRate: 250
      name: Sustained load
  payload:
    path: "simple-random-product-test.csv"
    fields:
      - "product_id1"
      - "product_id2"
      - "product_id3"
      - "product_id4"

scenarios:
  - name: "Browse products"
    flow:
      - get:
          url: "/qa/questions?product_id={{ product_id3 }}"
      - think: 15
      - get:
          url: "/qa/questions?product_id={{ product_id4 }}"