version: "3.9"
volumes:
  database:
    external: true
services:
  qanda-service:
    build: ./Dockerfile.api
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER: lawlorseanr
      - POSTGRES_PASSWORD: hackReactor
      - POSTGRES_DB: qanda
    volumes:
      - database:/var/lib/postgresql/data
